apiVersion: runway.aa.com/v1alpha1
kind: WebApp
metadata:
  name: autopilot-nonprod
  annotations:
    enableCloudIngress: "true"
    backstageName: autopilot-ui
  labels:
    app-id: autopilot-ui
    aa-app-shortname: APIMgmtGQL
    data-classification: nonpci
    environment: nonprod
spec:
  containerName: docker.aa.com/prod/autopilot-ui
  containerTag: 'v0.12.0'
  port: 3000
  healthCheck:
    endpoint: /
    enabled: False
    port: 3000
  secretProviders:
    - vault:
        vaultNamespace: automation/apimgmtgql-autopilotnp-p
        secretEngineMount: secrets
        secretPath: nonprod
  autoscale:
    minimum: 1
    maximum: 2
  reachableServices:
    - autopilot-agents-nonprod.autopilot-nonprod.svc.8000.mesh