apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: autopilot-ui
  description: "navigator ui frontend for project yoda genai application"
  annotations:
    github.com/project-slug: "AAInternal/autopilot-ui"
    argocd/app-selector: "backstage-name=autopilot-ui"
    backstage.io/kubernetes-label-selector: "backstage.io/kubernetes-id=autopilot-ui"
  tags:
    - node
    - yarn
    - genai
    - llm
    - chatbot
spec:
  type: service
  lifecycle: experimental
  owner: 'data-movement'
