services:
  frontend:
    container_name: autopilot-ui
    image: docker.aa.com/prod/autopilot-ui:v0.15.2 #localhost/autopilot-ui:latest
    ports:
      - "3000:3000"
    env_file:
      - .env

  agents:
    container_name: autopilot-agents
    image: docker.aa.com/prod/autopilot-agents:v0.10.0 #localhost/autopilot-agents:latest
    ports:
      - "8000:8000"
    env_file:
      - .env

  aa-graph-mcp-server:
    container_name: aa-graph-mcp-server
    image: docker.aa.com/prod/aa-graph-mcp-server:v0.3.0 #localhost/aa-graph-mcp-server:latest
    ports:
      - "8002:8000"
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: docker.aa.com/prod/pgvector/pgvector:pg17
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local