apiVersion: runway.aa.com/v1alpha1
kind: WebApp
metadata:
  name: navigator-ui
  annotations:
    enableCloudIngress: "true"
    backstageName: navigator-ui
  labels:
    app-id: navigator-ui
    aa-app-shortname: APIMgmtGQL
    data-classification: nonpci
    environment: prod
spec:
  containerName: docker.aa.com/prod/navigator-ui
  containerTag: 'v0.1.0'
  port: 3000
