apiVersion: runway.aa.com/v1alpha2
kind: Ephemeral
metadata:
  name: navigatoruiephemeral
  annotations:
    enableCloudIngress: "true"
    backstageName: autopilot-ui
  labels:
    app-id: autopilot-ui-nonprod
    runway.aa.com/aa-app-shortname: APIMgmtGQL
    data-classification: nonpci
    environment: nonprod
spec:
  repo: autopilot-ui
  maxEphemerals: 10
  maxDaysWithoutUpdate: 4
  template:
    containerName: docker.aa.com/nonprod/autopilot-ui
    containerTag: placeholder
    port: 3000
  env:
    - name: AUTH_WELLKNOWN
      value: 'https://idptest.aa.com/.well-known/openid-configuration'
    - name: NEXTAUTH_URL
      value: https://{{ .Context.EphemeralName }}.cloud.aa.com