name: CD

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
    paths-ignore:
        - "**/*.md"

permissions:
  contents: write
  id-token: write
  issues: read
  pull-requests: write

jobs:
  call-cd-reusable-workflows:
    name: CD
    if: github.event.pull_request.merged == true
    uses: AAInternal/dte-reusable-workflows/.github/workflows/cd_workflow.yaml@v6
    with:
      APP_NAME: autopilot-ui
      PR_NUMBER: ${{ github.event.pull_request.number }}
      CHERWELL_APP_NAME: 'Enterprise API Management (GraphQL)'   
      CHERWELL_BADGE_NUMBER: '00847763'
      CHERWELL_TEAM: 'TnT CEP Data Movement'
      CHERWELL_DESCRIPTION: 'Update to autopilot-ui frontend for project yoda genai application'
      CHERWELL_AFFECTED_CONFIG_ITEMS: 'autopilot-ui,autopilot-agents' # Required for Cherwell. List of Config Items being modified/affected. Multi line. 
      CHERWELL_APPLICATION_LOCATION: 'Azure East' # Required for Cherwell. List of Locations where application is live. Comma separated.
      AUTO_DEPLOY_K8s: "true"
      WEBAPP_YAML_FILE_PATH: "k8s/nonprod/webapp.yaml"  
    secrets: inherit