name: Dependabot Automation
on: 
  pull_request_target:
    branches: [ main ]
    
permissions:
  contents: write
  pull-requests: write
  id-token: write
  checks: read

jobs:
  dependabot-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          warn-only: true
  dependabot-autoapprove:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Generate Token
        uses: octo-sts/action@210248e8ae1ae1550aa6e232c6f192b3ccbf7335 # 210248e8ae1ae1550aa6e232c6f192b3ccbf7335
        id: octo-sts
        with:
          scope: AAInternal/autopilot-ui
          identity: yoda
          domain: octo-sts.cloud.aa.com
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve the PR for minor and patch dependencies
        id: approval
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{steps.octo-sts.outputs.token}}
      - name: Validate if all checks passed
        if: ${{ success() && steps.approval.outcome != 'skipped' }}
        id: checkspassed
        uses: wechuli/allcheckspassed@e22f45a4f25f4cf821d1273705ac233355400db1 # v1
      - name: Enable auto-merge
        if: ${{ success() && steps.approval.outcome != 'skipped' }}
        run: |
          gh pr merge "$PR_URL" --auto --squash
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{steps.octo-sts.outputs.token}}