name: Docker Image Changelog

on:
  pull_request_target:
    branches: [master]
    paths:
      - '**/Dockerfile'

jobs:
  generate-changelog:
    uses: AAInternal/container-base-images/.github/workflows/generate_changelog.yaml@v1
    if: contains(github.actor, 'dependabot') == true
    permissions:
      id-token: write
      pull-requests: write
      issues: write
      contents: read
    with:
      create-comment: true
      create-pull-request-labels: true