name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version to promote"
        required: true
        default: "v0.0.0"
      environment:
        description: 'Environment to promote version'
        type: choice
        default: 'nonprod'
        options:
          - nonprod
          - prod

env:
  CHERWELL_APP_NAME: "Enterprise API Management (GraphQL)"
  CHERWELL_BADGE_NUMBER: "00847763"
  CHERWELL_TEAM: "TnT CEP Data Movement"
  CHERWELL_DESCRIPTION: "Update to autopilot-ui service"
  CHERWELL_CHANGE_PROPOSED_START_DATETIME: ""
  CHERWELL_CHANGE_PROPOSED_END_DATETIME: ""
  CHERWELL_ENVIRONMENT: ""
  CHERWELL_AFFECTED_CONFIG_ITEMS: "autopilot-ui,autopilot-agents"
  CHERWELL_APPLICATION_LOCATION: "Azure East, Azure West"

jobs:
  promote:
    name: Update Container Tag Version on webapp.yaml
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Generate Token
        uses: octo-sts/action@210248e8ae1ae1550aa6e232c6f192b3ccbf7335 # 210248e8ae1ae1550aa6e232c6f192b3ccbf7335
        id: octo-sts
        with:
          scope: AAInternal/autopilot-ui
          identity: yoda
          domain: octo-sts.cloud.aa.com

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{steps.octo-sts.outputs.token}}
          fetch-depth: 0

      - name: Update webapp.yaml
        run: |
          yq eval ".spec.containerTag |= \"${{ inputs.version }}\"" --inplace k8s/${{ inputs.environment }}/webapp.yaml
          git config --global user.email "githubactions@aa.com"
          git config --global user.name "Github Actions"
          git add k8s/${{ inputs.environment }}/webapp.yaml
          git commit -m "Update Version to ${{ inputs.version }}"
          git push origin HEAD:main

      - name: Validate AA Yaml
        uses: AAInternal/aa-yaml-validator@v2.3.1
        id: aa-yaml

      # The URL for tower action is https://github.com/AAInternal/tower-action
      - name: Call Tower
        if: ${{ inputs.environment == 'current' }}
        uses: AAInternal/tower-action@caf0395ed37e01720085a34edcccde0908e9cfe7 # v2.5.0
        with:
          tower_url: ${{ secrets.TOWER_URL }} # AAInternal User Credential
          token_url: ${{ secrets.TOWER_TOKEN_URL }} # AAInternal Organizational secret
          client_id: ${{ secrets.TOWER_USR }} # AAInternal User Credential
          client_secret: ${{ secrets.TOWER_PWD }} # AAInternal User Credential
          archer_short_name: ${{ steps.aa-yaml.outputs.cmdbAppShortName }}
          squad360_id: ${{ steps.aa-yaml.outputs.squad }}

      - name: Create Cherwell Change Request
        if: ${{ inputs.environment == 'current' }}
        uses: AAInternal/enterprise-change-action@44d74f71de3896e6beb1f590541d27d9095510fb # v0
        with:
          username: ${{ secrets.CHERWELL_USR }}
          password: ${{ secrets.CHERWELL_PWD }}
          client_id: ${{ secrets.CHERWELL_CID }}
          appName: ${{ env.CHERWELL_APP_NAME }} # Application name based on what is shown in Archer
          badgeNumber: ${{ env.CHERWELL_BADGE_NUMBER }} # 8 Digit AAID
          team: ${{env.CHERWELL_TEAM }} # Cherwell Team Name
          description: ${{ env.CHERWELL_DESCRIPTION }} # Description of change request
          changeArtifactLocation: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" # Location where evidence for build/testing/deployments for this change resides
          affectedConfigItems: ${{ env.CHERWELL_AFFECTED_CONFIG_ITEMS }} # List of Config Items being modified/affected. Multi line.
          applicationLocation: ${{ env.CHERWELL_APPLICATION_LOCATION }} # List of Locations where application is live. Comma separated.
          changeProposedStartDateTime: ${{ env.CHERWELL_CHANGE_PROPOSED_START_DATETIME }} # Change Start Time format '5/15/2023T20:00:00'
          changeProposedEndDateTime: ${{ env.CHERWELL_CHANGE_PROPOSED_END_DATETIME }} # Change End Time format '5/16/2023T20:00:00'
          cherwell_environment: ${{ env.CHERWELL_ENVIRONMENT }} # Optional. Defaults to Prod.